warehouse:
  api:
    url-prefix: http://localhost:8080
amqp:
  topic:
    order-status: "q.order_status"
    delivery: "q.delivery"

server:
  port: 8081

logging:
  level:
    org:
      springframework:
        security: DEBUG
spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: checkout-service
            client-secret: 5pv6GlBYGdW2ahvoB689AIQyAbEv4owg
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            token-uri: http://localhost:9091/realms/warehouse-microservices/protocol/openid-connect/token
            issuer-uri: http://localhost:9091/realms/warehouse-microservices
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9091/realms/warehouse-microservices
          jwk-set-uri: http://localhost:9091/realms/warehouse-microservices/protocol/openid-connect/certs
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
